export default [
  { ingredient: 'Espaguetis', qty: { amount: 500, units: 'g' } },
  { ingredient: 'ajo', qty: { amount: 8, units: undefined } },
  { ingredient: 'aceite', qty: {} },
  { ingredient: 'Parmesano', qty: { amount: 100, units: 'g' } },
  { ingredient: 'judias verdes', qty: { amount: 1, units: 'kg' } },
  { ingredient: 'tomate', qty: { amount: 3 } },
  { ingredient: 'cebolla', qty: { amount: 4, units: undefined } },
  { ingredient: 'Patatas', qty: { amount: 2, units: undefined } },
  { ingredient: 'sal', qty: {} },
  { ingredient: 'Lentejas', qty: { amount: 2, units: 'kg' } },
  {
    ingredient: 'zanahoria',
    qty: { amount: 8, units: undefined },
  },
  {
    ingredient: 'chorizo para guisar',
    qty: { amount: 2, units: undefined },
  },
  { ingredient: 'Panceta', qty: { amount: 2, units: 'lonchas' } },
  {
    ingredient: 'Salsa de soja',
    qty: { amount: 25, units: 'ml' },
  },
  { ingredient: 'Eneldo', qty: undefined },
  { ingredient: 'salmon', qty: { amount: 2, units: 'lomos' } },
  {
    ingredient: 'Alcachofas',
    qty: { amount: 8, units: undefined },
  },
  { ingredient: 'Arroz', qty: { amount: 100, units: 'g' } },
  { ingredient: 'nata', qty: { amount: 200, units: 'ml' } },
  { ingredient: 'coliflor', qty: { amount: 2, units: undefined } },
  { ingredient: 'leche', qty: { amount: 2, units: 'l' } },
  { ingredient: 'queso', qty: { amount: 200, units: 'g' } },
  { ingredient: 'mantequilla', qty: { amount: 300, units: 'g' } },
  { ingredient: 'harina', qty: { amount: 300, units: 'g' } },
  { ingredient: 'pimienta negra', qty: {} },
  { ingredient: 'nuez moscada', qty: {} },
  {
    ingredient: 'Pollo de corral',
    qty: { amount: 4, units: 'contramuslos' },
  },
  { ingredient: 'Caldo de pollo', qty: { amount: 1, units: 'l' } },
];
